FROM nginx:1.17.8-alpine

RUN mkdir /etc/nginx/ssl
COPY conf/nginx/ssl/snakeoil.crt /etc/nginx/ssl/snakeoil.crt
COPY conf/nginx/ssl/snakeoil.key /etc/nginx/ssl/snakeoil.key

COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/kolide.conf /etc/nginx/conf.d/kolide.conf